# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development, master ]
  pull_request:
    branches: [ development, master ]
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
    # Runs a single command using the runners shell
      - name: Run e2e test
        run: cd server && npm install && npm run test
        env: 
          TEST_DATABASE_URL:  ${{ secrets.TEST_DATABASE_URL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
